if (global.apariencia == 1)
{
    switch argument0
    {
        case 433:
            return snd_voice_ground;
        case 108:
            return snd_voice_item_block;
        case 111:
            return snd_voice_hidden_block;
        case 112:
            return snd_voice_block;
        case 122:
            return snd_voice_cloud_block;
        case 118:
            return snd_voice_hard_block;
        case 119:
            return snd_voice_ice_block;
        case obj_hongo1:
            return snd_voice_mashroom_platform;
        case obj_dec3:
            return snd_voice_semisolid_platform;
        case obj_puente:
            return snd_voice_puente;
        case 138:
            return snd_voice_donut_block;
        case 128:
            return snd_voice_spike_trap;
        case 166:
            return snd_voice_pipe;
        case 113:
            return snd_voice_note_block;
        case 114:
            return snd_voice_note_block;
        case 142:
            return snd_voice_coin;
        case 144:
            return snd_voice_pink_coin;
        case 199:
            return snd_voice_mushroom;
        case 200:
            return snd_voice_fire_flower;
        case 203:
            return snd_voice_leaf;
        case 198:
            return snd_voice_1up;
        case 214:
            return snd_voice_shoe;
        case 223:
            return snd_voice_shoe_red;
        case 206:
            return snd_voice_star;
        case 145:
            return snd_voice_10_coin;
        case 146:
            return snd_voice_30_coin;
        case 147:
            return snd_voice_50_coin;
        case 25:
            return snd_voice_goomba;
        case 26:
            return snd_voice_goombrat;
        case 28:
            return snd_voice_koopa;
        case 29:
            return snd_voice_koopa;
        case 67:
            return snd_voice_bobomb;
        case 69:
            return snd_voice_lit_bobomb;
        case 34:
            return snd_voice_buzzy;
        case 35:
            return snd_voice_spiny;
        case 84:
            return snd_voice_hammerbro;
        case 85:
            return snd_voice_sledgebro;
        case 37:
            return snd_voice_piranha_plant;
        case 38:
            return snd_voice_fire_plant;
        case 61:
            return snd_voice_drybones;
        case 62:
            return snd_voice_thwomp;
        case 64:
            return snd_voice_lavabubble;
        case 40:
            return snd_voice_cheepcheep;
        case 126:
            return snd_voice_muncher;
        case 83:
            return snd_voice_boomboom;
        case 42:
            return snd_voice_blooper;
        case 43:
            return snd_voice_sun;
        case 80:
            return snd_voice_chomp;
        case 66:
            return snd_voice_magikoopa;
        case 82:
            return snd_voice_bowser;
        case 152:
            return snd_voice_pswitch;
        case 154:
            return snd_voice_pow_block;
        case 148:
            return snd_voice_spring;
        case 149:
            return snd_voice_spring;
        case 167:
            return snd_voice_door;
        case 169:
            return snd_voice_p_door;
        case 65:
            return snd_voice_grinder;
        case 233:
            return snd_voice_clown;
        case 234:
            return snd_voice_fire_clown;
        case 134:
            return snd_voice_cinta;
        case obj_cinta_fast:
            return snd_voice_cinta;
        case obj_platform_moving:
            return snd_voice_platform;
        case obj_platform_falling:
            return snd_voice_platform_fall;
        case 132:
            return snd_voice_arrow;
        case 156:
            return snd_voice_bumper;
        case 70:
            return snd_voice_bill_blaster;
        case 164:
            return snd_voice_torbellino;
        case 16:
            return snd_voice_checkpoint;
        case 74:
            return snd_voice_bill_banzai;
        case 115:
            return snd_voice_onoff_switch;
        case 116:
            return snd_voice_onoff_block;
        case 117:
            return snd_voice_onoff_block;
        case 130:
            return snd_voice_estalactita;
        case 131:
            return snd_voice_estalactita;
        case 161:
            return snd_voice_key;
        case 171:
            return snd_voice_key_door;
    }
    
}
else if (global.apariencia == 2)
{
    switch argument0
    {
        case 433:
            return snd_voice_ground;
        case 108:
            return snd_voice_item_block;
        case 111:
            return snd_voice_hidden_block;
        case 112:
            return snd_voice_block;
        case 122:
            return snd_voice_cloud_block;
        case 118:
            return snd_voice_hard_block;
        case 119:
            return snd_voice_ice_block;
        case obj_hongo1:
            return snd_voice_mashroom_platform;
        case obj_dec3:
            return snd_voice_semisolid_platform;
        case obj_puente:
            return snd_voice_puente;
        case 138:
            return snd_voice_donut_block;
        case 128:
            return snd_voice_spike_trap;
        case 166:
            return snd_voice_pipe;
        case 113:
            return snd_voice_note_block;
        case 114:
            return snd_voice_note_block;
        case 142:
            return snd_voice_coin;
        case 144:
            return snd_voice_pink_coin;
        case 199:
            return snd_voice_mushroom;
        case 200:
            return snd_voice_fire_flower;
        case 203:
            return snd_voice_cap;
        case 198:
            return snd_voice_1up;
        case 214:
            return snd_voice_yoshi;
        case 223:
            return snd_voice_red_yoshi;
        case 206:
            return snd_voice_star;
        case 145:
            return snd_voice_10_coin;
        case 146:
            return snd_voice_30_coin;
        case 147:
            return snd_voice_50_coin;
        case 25:
            return snd_voice_goomba;
        case 26:
            return snd_voice_goombrat;
        case 28:
            return snd_voice_koopa;
        case 29:
            return snd_voice_koopa;
        case 67:
            return snd_voice_bobomb;
        case 69:
            return snd_voice_lit_bobomb;
        case 34:
            return snd_voice_buzzy;
        case 35:
            return snd_voice_spiny;
        case 84:
            return snd_voice_hammerbro;
        case 85:
            return snd_voice_sledgebro;
        case 37:
            return snd_voice_piranha_plant;
        case 38:
            return snd_voice_fire_plant;
        case 61:
            return snd_voice_drybones;
        case 62:
            return snd_voice_thwomp;
        case 64:
            return snd_voice_lavabubble;
        case 40:
            return snd_voice_cheepcheep;
        case 126:
            return snd_voice_muncher;
        case 83:
            return snd_voice_boomboom;
        case 42:
            return snd_voice_blooper;
        case 43:
            return snd_voice_sun;
        case 80:
            return snd_voice_chomp;
        case 66:
            return snd_voice_magikoopa;
        case 82:
            return snd_voice_bowser;
        case 152:
            return snd_voice_pswitch;
        case 154:
            return snd_voice_pow_block;
        case 148:
            return snd_voice_spring;
        case 149:
            return snd_voice_spring;
        case 167:
            return snd_voice_door;
        case 169:
            return snd_voice_p_door;
        case 65:
            return snd_voice_grinder;
        case 233:
            return snd_voice_clown;
        case 234:
            return snd_voice_fire_clown;
        case 134:
            return snd_voice_cinta;
        case obj_cinta_fast:
            return snd_voice_cinta;
        case obj_platform_moving:
            return snd_voice_platform;
        case obj_platform_falling:
            return snd_voice_platform_fall;
        case 132:
            return snd_voice_arrow;
        case 156:
            return snd_voice_bumper;
        case 70:
            return snd_voice_bill_blaster;
        case 164:
            return snd_voice_torbellino;
        case 16:
            return snd_voice_checkpoint;
        case 74:
            return snd_voice_bill_banzai;
        case 115:
            return snd_voice_onoff_switch;
        case 116:
            return snd_voice_onoff_block;
        case 117:
            return snd_voice_onoff_block;
        case 130:
            return snd_voice_estalactita;
        case 131:
            return snd_voice_estalactita;
        case 161:
            return snd_voice_key;
        case 171:
            return snd_voice_key_door;
    }
    
}